services:
  traefik:
    container_name: traefik
    image: "traefik:v2.0"
    restart: always
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.web-resolver-inenpla.acme.tlschallenge=true"
      #- "--certificatesresolvers.web-resolver-inenpla.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.web-resolver-inenpla.acme.email=devops@vonbraunlabs.com.br"
      - "--certificatesresolvers.web-resolver-inenpla.acme.storage=/letsencrypt/acme.json"
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  inenpla-api:
    container_name: "inenpla-marelli-api"
    depends_on:
      - traefik
    image: "inenpla-marelli-api:latest"
    restart: always
    environment:
      - AWS__Region=${AWS__Region}
      - AWS__BucketName=${AWS__BucketName}
      - AWS__SecretName=${AWS__SecretName}
      - AppSettings__UrlHost=${AppSettings__UrlHost}
      - Jenkins__UrlHost=${Jenkins__UrlHost}
      - Jenkins__Token=${Jenkins__Token}
    labels:
      - "traefik.enable=true"
      # Configura balanceamento para a porta 80
      - "traefik.http.services.inenpla-api.loadbalancer.server.port=80"

      # Habilita os certificados tls
      - "traefik.http.routers.web-router-inenpla-api.tls=true"
      - "traefik.http.routers.web-router-inenpla-api.rule=Host(`${dnsApiNameserver}`)"
      - "traefik.http.routers.web-router-inenpla-api.entrypoints=websecure"
      - "traefik.http.routers.web-router-inenpla-api.tls.certresolver=web-resolver-inenpla"
    networks:
      - traefik-network
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${postgresUser}
      POSTGRES_PASSWORD: ${postgresPassword}
    networks:
      - traefik-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  traefik-network:
